version: '3'
services:
  database:
    image: 'mongo'
    container_name: 'app-management-db'
    environment:
      - MONGO_INITDB_DATABASE=app-management
      - MONGO_INITDB_ROOT_USERNAME=appadmin
      - MONGO_INITDB_ROOT_PASSWORD=1234
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - 27017-27019:27017-27019